[tool.poetry]
name = "rosa-python-client"
version = "1.0.7"
description = "Wrapper for rosa cli"
authors = ["Meni Yakove <myakove@gmail.com>"]
readme = "README.md"
packages = [{include = "rosa"}]

[tool.poetry.dependencies]
python = "^3.8"
python-simple-logger = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
